// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/wyuhsin/web-template-go/internal/biz"
	"github.com/wyuhsin/web-template-go/internal/conf"
	"github.com/wyuhsin/web-template-go/internal/data"
	"github.com/wyuhsin/web-template-go/internal/server"
	"github.com/wyuhsin/web-template-go/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	server_GRPC := confServer.Grpc
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(logger, greeterUsecase)
	grpcServer := server.NewGRPCServer(server_GRPC, logger, greeterService)
	server_HTTP := confServer.Http
	httpServer := server.NewHTTPServer(server_HTTP, logger, greeterService)
	rabbitmqServer := server.NewRabbitMQServer(confServer, logger, greeterService)
	mqttServer := server.NewMQTTServer(confServer, logger, greeterService)
	websocketServer := server.NewWebsocketServer(confServer, logger, greeterService)
	server_TCP := confServer.Tcp
	tcpServer := server.NewTCPServer(server_TCP, logger)
	server_UDP := confServer.Udp
	udpServer := server.NewUDPServer(server_UDP, logger)
	app := newApp(logger, grpcServer, httpServer, rabbitmqServer, mqttServer, websocketServer, tcpServer, udpServer)
	return app, func() {
		cleanup()
	}, nil
}
