// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/sirupsen/logrus"
	"github.com/wyuhsin/web-template-go/internal/biz"
	"github.com/wyuhsin/web-template-go/internal/data"
	"github.com/wyuhsin/web-template-go/internal/pkg/dbx"
	"github.com/wyuhsin/web-template-go/internal/pkg/tracingx"
	"github.com/wyuhsin/web-template-go/internal/server"
	"github.com/wyuhsin/web-template-go/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(config *server.Config, dataConfig *data.Config, tracingxConfig *tracingx.Config, entry *logrus.Entry) (*kratos.App, func(), error) {
	grpcConfig := &config.GRPC
	mySQLConfig := dataConfig.MySQL
	mySQLDB, cleanup, err := dbx.NewMySQLDB(mySQLConfig, entry)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := dataConfig.Redis
	client, cleanup2, err := dbx.NewRedisClient(redisConfig, entry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(mySQLDB, client, entry)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, entry)
	greeterService := service.NewGreeterService(entry, greeterUsecase)
	grpcServer := server.NewGRPCServer(grpcConfig, tracingxConfig, entry, greeterService)
	httpConfig := &config.HTTP
	systemService := service.NewSystemService()
	httpServer := server.NewHTTPServer(httpConfig, tracingxConfig, entry, greeterService, systemService)
	rabbitmqServer := server.NewRabbitMQServer(config, entry, greeterService)
	mqttServer := server.NewMQTTServer(config, entry, greeterService)
	websocketServer := server.NewWebsocketServer(config, entry, greeterService)
	tcpConfig := &config.TCP
	tcpServer := server.NewTCPServer(tcpConfig, entry)
	udpConfig := &config.UDP
	udpServer := server.NewUDPServer(udpConfig, entry)
	app := newApp(entry, grpcServer, httpServer, rabbitmqServer, mqttServer, websocketServer, tcpServer, udpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
